add log

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,6 +34,15 @@ jobs:
       - name: Verify Authentication
         run: gcloud auth list
 
+      - name: Check if Secret is Available
+        run: |
+          if [[ -z "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" ]]; then
+            echo "❌ Secret is missing!"
+            exit 1
+          else
+            echo "✅ Secret is set!"
+          fi
+
       - name: ☁️ Deploy to GCP Storage Bucket
         run: |
           gsutil -m rsync -r ./dist gs://${{secrets.BUCKET_NAME}}
